# Generated by Django 6.1.1 on 2026-09-21 15:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='absencereport',
            name='declined_substitutes',
            field=models.ManyToManyField(blank=True, help_text='Faculty who explicitly declined this substitution request.', limit_choices_to={'role': 'faculty'}, related_name='substitution_requests_declined', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='absencereport',
            name='notified_substitutes',
            field=models.ManyToManyField(blank=True, help_text='All eligible faculty who received this substitution request.', limit_choices_to={'role': 'faculty'}, related_name='substitution_requests_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='absencereport',
            name='confirmation_deadline',
            field=models.DateTimeField(blank=True, help_text='Deadline by which a substitute must confirm.', null=True),
        ),
    ]
